//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentsManger
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Room
    {
        public int IDRoom { get; set; }
        [Required]
        [Range(1,9999, ErrorMessage ="Room's number cannot be over 9999.")]
        public int Number { get; set; }
        [Required]
        [Range(1, 8, ErrorMessage = "Capacity cannot be over 8 people.")]
        public int Capacity { get; set; }
        [Required]
        [Display(Name ="ApartmentID")]
        public int ApartmentIDApartment { get; set; }
        [Display(Name = "UploadedFile")]
        public int UploadedFileID { get; set; }
    
        public virtual Apartment Apartment { get; set; }
    }
}
